name: lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  lintr:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "lintr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Lint package
        run: lintr::lint_package()
        shell: Rscript {0}

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: r-lib/actions/setup-r@v1

#       - name: Install dependencies 
#         run: |
#           install.packages(c("remotes"))
#           remotes::install_deps(dependencies = TRUE)
#           remotes::install_cran("lintr")
#           remotes::install_cran("styler")
#         shell: Rscript {0}


#       - name: Install package
#         run: R CMD INSTALL .

  
#       - name: style
#         run: styler::style_dir()
#         shell: Rscript {0}
  

#       - name: Lint
#         run: lintr::lint_dir()
#         shell: Rscript {0}
#         # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
