
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: lint-project

jobs:
  lint-project:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install lintr
        run: install.packages(c("lintr", "styler"))
        shell: Rscript {0}
        
      - name: Style root directory
        run: Rscript -e 'styler::style_dir()'
      - name: commit
        run: |
          git config --local user.email "samaravazquezperez@ada-mode.com"
          git config --local user.name "samaravazquezperez"
          git add \*.R
          git commit -m 'Style'
      - uses: r-lib/actions/pr-push@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint root directory
        run: lintr::lint_dir()
        shell: Rscript {0}

