
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: lint-project

jobs:
  lint-project:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install lintr
        run: |
          install.packages(c("lintr", "styler", 'remotes', 'testthat')) 
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Style root directory
        run: >
          Rscript
          -e "error<-lintr::lint_dir()"
          -e "print(error)"
          -e "if(length(error)>1){styler::style_dir()}"
      - name: commit
        if: ${{ success() }}
        run: |
          git config --local user.email "samaravazquezperez@ada-mode.com"
          git config --local user.name "samaravazquezperez"
          git add \*.R
          git commit -am 'Style'
      - name: Unit testing
        run: testthat::test_dir('tests/testthat')
        shell: Rscript {0}
      - name: Check status
        if: ${{ failure() }}
        run: |
          git reset HEAD^ --hard
          git push origin -f
      
