on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: format-project

jobs:
  lint-project:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
  
        run: |
          install.packages(c("lintr", "styler", 'remotes', 'testthat')) 
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Style root directory
        run: styler::style_dir()
        shell: Rscript {0}

      - name: Lint root directory
        run: lintr::lint_dir()
        shell: Rscript {0}
        
      - name: Unit testing
        run: testthat::test_dir('tests/testthat')
        shell: Rscript {0}
