
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: lint-project

jobs:
  lint-project:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
      - name: Query dependencies 
        run: |   
          install.packages('remotes') 
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2) 
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version") 
        shell: Rscript {0} 
  
      - name: Cache R packages 
        if: runner.os != 'Windows' 
        uses: actions/cache@v1 
        with: 
          path: ${{ env.R_LIBS_USER }} 
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }} 
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1- 
      # - name: Install lintr
      #   run: |
      #     install.packages(c("lintr", "styler", 'remotes', 'testthat')) 
         # remotes::install_deps(dependencies = TRUE)
       # shell: Rscript {0}
      - name: Style root directory
        run: >
          Rscript
          -e "error<-lintr::lint_dir()"
          -e "print(error)"
          -e "if(length(error)>1){styler::style_dir()}"
      - name: commit
        run: |
          git config --local user.email "samaravazquezperez@ada-mode.com"
          git config --local user.name "samaravazquezperez"
          git add \*.R
          git commit -am 'Style'
      - name: Unit testing
        run: testthat::test_dir('tests/testthat')
        shell: Rscript {0}
      - name: Check status
        if: ${{ failure() }} || -z [git status --porcelain] 
        run: |
          git reset HEAD^ --hard
          git push origin -f
      - name: Check status
        if: ${{ success() }}
        run: git push
      
